version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=stefan
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
